### ISSUE TITLE
Typing

### ISSUE THREAD

**Issue by davetapley** [Knio/dominate#207] opened 2024-09-21 00:50 UTC
👍🏻 if there is appetite for [`typing`](https://docs.python.org/3/library/typing.html).

I'm going to start working on my own stubs, but will share here if requested.

**Comment by lgarron** [comment] 2024-11-19 11:29
I started using `dominate` for a small side project a long time ago, but if I was making a decision from scratch for a Python project then typing support would be make-or-break for me.

**Comment by Knio** [comment] 2024-11-26 17:16
Duplicate of #191

**Closed by Knio** 2024-11-26 17:16 UTC
